import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Wrapper from "./Wrapper";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Provider } from 'jotai'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  locale: never;
};

export default async function RootLayout({children, locale}: Props){
  const messages = await getMessages()
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen h-screen font-roboto text-black font-normal bg-bodyBackground`}
      >
        <NextIntlClientProvider messages={messages}>
          <Provider>
            <Wrapper>
              {children}
            </Wrapper>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
